### ISSUE TITLE
When will the code be open source?

### ISSUE THREAD

**Issue by Huzhen757** [microsoft/DynamicHead#5]
Hello, I'm very interested in your improvements in the Head section. When will the code be open source?

Thanks!

**Comment by vdavid70619** [comment]
Thanks for your interests! The code is released now. Please check it out.

**Comment by Huzhen757** [comment]
Ok！&nbsp;Thank&nbsp;you&nbsp;very&nbsp;much！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/DynamicHead"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月1日(星期一) 上午6:08
***@***.***&gt;;
抄送:&nbsp;"Hide on ***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/DynamicHead] When will the code be open source? (#5)





 
Thanks for your interests! The code is released now. Please check it out.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
